spring.application.name=Autodoc

# Conexión automática con Azure Key Vault
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://compmarketperu.vault.azure.net/
azure.keyvault.tenant-id=7504e318-8e1e-4d55-bffd-875b4dee8260

# Especificamos el driver ya que Hibernate lo requiere para inicializar el pool
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# El dialecto ya no es necesario especificarlo explícitamente en Spring Boot 3
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Configuración del Servidor y Logs
server.port=8080
spring.thymeleaf.cache=false

logging.level.com.azure.spring=DEBUG
logging.level.org.springframework.cloud.azure=DEBUG
logging.level.com.autodoc=INFO
logging.level.org.springframework.security=DEBUG