spring.application.name=Autodoc

# Debe coincidir con CompMarketPeruDB creada por autodoc_database_script.txt
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_name}
spring.datasource.password=${BD_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# El esquema ya lo crea el script SQL -> ddl-auto=none (Hibernate no debe tocar la estructura)

spring.jpa.hibernate.ddl-auto=update
#Cambiar segun sea el caso spring.jpa.hibernate.ddl-auto=update --> update = segun el app actulizar la bd || 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false

server.port=8080

logging.level.com.autodoc=INFO
logging.level.org.springframework.security=DEBUG
