spring.application.name=Autodoc

# Azure Key Vault

spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=${AZURE_KEYVAULT_URL}

# DataSource desde Key Vault
spring.datasource.url=${bd-url}
spring.datasource.username=${bd-username}
spring.datasource.password=${bd-password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Puerto dinámico para Azure
server.port=${PORT:8080}

spring.thymeleaf.cache=false

logging.level.com.azure.spring=DEBUG
logging.level.org.springframework.cloud.azure=DEBUG
logging.level.com.autodoc=INFO
logging.level.org.springframework.security=DEBUG